import Head from "next/head";
import Image from "next/image";
import Profile from "../components/Profile";
import { Profile2 } from "../components/Profile2";

export default function Home() {
  return (
    <div className='flex flex-col min-h-screen w-full'>
      <Head>
        <title>Nemiwind</title>
        <meta name="description" content="Generated by Nemiwind" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"flex flex-col space-y-8 h-[800px] w-full justify-between mt-24 items-center"}>
        <div className="flex flex-col w-full justify-center items-center">
          <div className="flex flex-col justify-end items-end">
            <a href="https://nextjs.org" className='text-4xl font-extrabold lowercase tracking-tighter italic'>Nemiwind</a>
            <h1 className={"font-light text-sm"}>
          A Nextjs, Wagmi, Tailwind starter site for instant experimentation
            </h1>
          </div>
        </div>

        {/* <Profile /> */}
        <Profile2 />

        <div className={"grid h-full cursor-default"}>
          <a
            href="https://nextjs.org/docs/getting-started"
            className={"flex flex-col cursor-default"}
          >
            <h2 className='dependency-section'>HTML/React Framework: Next &rarr;</h2>
            {/* insert Next bio */}
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, possimus?</p>
          </a>

          <a href="https://tailwindcss.com/docs/guides/nextjs" className={"flex flex-col cursor-default"}>
            <h2 className='dependency-section'>CSS Framework: Tailwind &rarr;</h2>
            {/* insert tailwind bio */}
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, doloribus?</p>
          </a>

          <a href="https://wagmi.sh/docs/getting-started" className={"flex flex-col cursor-default"}>
            <h2 className='dependency-section'>Ethereum Access: WAGMI &rarr;</h2>
            {/* insert wagmi bio */}
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, possimus?</p>
          </a>
        </div>
      </main>
    </div>
  );
}
